[versions]
kotlin = "1.8.10"
tomlj = "1.1.0"
junit = "4.13.2"
plugin-publish = "1.0.0"
mockito = "4.8.0"
truth = "0.44"
agp-version = "8.3.0-dev"
sdk-version = "31.3.0-dev"
coroutines = "1.6.4"
intellij = "1.13.2"
changelog = "1.3.1"

[libraries]
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
junit = { module = "junit:junit", version.ref="junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
testutils = { module = "com.android.tools:testutils", version.ref = "sdk-version" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
toolsCommon = { module = "com.android.tools:common", version.ref = "sdk-version"}
declarativeModel = { module = "com.android.tools.build.declarative:model", version.ref = "agp-version" }
agpApi = { module = "com.android.tools.build:gradle-api", version.ref = "agp-version" }
testFramework = { module = "com.android.build.integration-test:framework", version.ref = "agp-version" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
plugin-publish =  { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
gradle-intellij = { id = "org.jetbrains.intellij", version.ref = "intellij"}
gradle-intellij-changelog = { id = "org.jetbrains.changelog", version.ref = "changelog"}
